profiles: dev

server:
  port: 8082

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/platform_test?useUnicode=true&characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

security:
  user: admin
  password: inventory

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000
feign:
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true # 开始数据压缩
      mime-types:   # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048个字节进行压缩

logging:
  level:
    com.cloud.work.order: DEBUG